#Player Command Logger Config

#   Debug ( max / full / Default:normal / stop )
Debug: normal

#   MySQL Settings
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: CommandLogger
  username: root
  password: password

#   File out
File: false

#   No Logging Command
NoWrite:
    - home
    - spawn

NoPlayer:
    - Kumaisu
