main: com.mycompany.commandlogger.CommandLogger
name: CommandLogger
version: ${project.version}
description: ${project.description}
author: Kumaisu
database: true
api-version: 1.14
commands:
    logger:
        description: Player Command Log Admins
        usage: /<command>
permissions:
    CommandLogger.admin:
        permission-message: You do not have permission.
    CommandLogger.view:
        description: Show Other Player Command
