main: io.github.kumaisu.commandlogger.CommandLogger
name: CommandLogger
version: 0.3.0
description: Player Command Log plugin
author: Kumaisu
database: true
api-version: '1.21'
commands:
    logger:
        description: Player Command Log Admins
        usage: /<command>
permissions:
    CommandLogger.admin:
        permission-message: You do not have permission.
    CommandLogger.view:
        description: Show Other Player Command
